/msgcom:
  ros__parameters:
    uart_serialterminal: /dev/ttyUSB0
    serial_baudrate: 115200
    ackermann_topic: /control/drive
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

